name: CI Voll Med
#Toda vez que um novo código é adicionada a main ou pull_request, vai rodar o pipeline.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#Esse comando vai especificar que esse job vai rodar em uma máquina virtual Ubuntu mais recente.
jobs:
  build:

    runs-on: ubuntu-latest
#Esse passo vai fazer com que o código do nosso repositório seja clonado para a VM do nosso pipeline.
    steps:
    - uses: actions/checkout@v3
    
    - name: Configura JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Configura o Docker Compose
      run: |
        sudo rm -f /usr/local/bin/docker-compose
        curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
        
    - name: Roda o Docker Compose
      run: docker-compose up -d
      
    - name: Executa os testes unitários
      run: mvn -B verify
    - name: Gera relatorio jacoco
      run: mvn jacoco:prepare-agent verify
      
    - name: Analise estatica
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=portel4_vollmed-api
